### PR TITLE
Feature/buttons control

### PR DESCRIPTION
**Pull request by texx00**
Adding the possibility to control the table with some hw buttons

### CODE REVIEW

**Comment by texx00** [comment]
Not tested on real hw yet

**Comment by texx00** [comment]
Will need to use docker (#8) in order to simplify the installation for the hw part. Using the GPIO library is messing up even more with the sudo command than the standard stuff... Using sudo is necessary for some write permissions but using sudo make useless the virtual enviroment. But since the environment is created, flask will use it and will not find the libraries installed with apt-get which requires sudo i.e. the files are not installed for the environment but globally -> flask will not find the correct libraries.
Added a workaround for this in the installation instructions

**Comment by texx00** [comment]
The buttons are working even if the functions are limited. Will come back in a while to update this. For the moment will merge like this. 

Will be better to detach the function from the click or long press into two different menues.
Should also add the possibility to choose between pullup-pulldown- nopullup-nopulldown

**Comment by vincentbraillard** [comment]
Nice.

I will check the setting file.

May be that can help you

https://github.com/jgarff/rpi_ws281x



Le mar. 13 juil. 2021 à 19:27, Luca Tessaro ***@***.***> a
écrit :

**Pull request merged**
